version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "waytrek-api"
s3_bucket = ""
s3_prefix = "waytrek-api"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = ""
image_repositories = []

[default.build]
[default.build.parameters]
use_container = true