"""create tables: trip_documents, trip_schedule, schedule, activity_videos

Revision ID: 98b9ecd978f8
Revises: 0ae7e9d24f88
Create Date: 2025-06-05 10:21:26.002975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b9ecd978f8'
down_revision: Union[str, None] = '0ae7e9d24f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_schedule_id', sa.Integer(), nullable=True),
    sa.Column('hour', sa.String(), nullable=False),
    sa.Column('activity_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['trip_schedule_id'], ['trip_schedule.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('activities', sa.Column('history', sa.String(), nullable=False))
    op.add_column('activities', sa.Column('tip', sa.String(), nullable=False))
    op.add_column('activities', sa.Column('movie', sa.String(), nullable=False))
    op.add_column('activities', sa.Column('clothes', sa.String(), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('cognito_id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('user_type_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['cognito_id'])
    op.create_foreign_key(None, 'users', 'users_types', ['user_type_id'], ['id'], ondelete='cascade')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'user_type_id')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'cognito_id')
    op.drop_column('users', 'name')
    op.drop_column('activities', 'clothes')
    op.drop_column('activities', 'movie')
    op.drop_column('activities', 'tip')
    op.drop_column('activities', 'history')
    op.drop_table('schedule')
    op.drop_table('trip_schedule')
    op.drop_table('trip_documents')
    op.drop_table('activity_videos')
    # ### end Alembic commands ###
